import type { Metadata } from "next";
import { Quicksand } from 'next/font/google';
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Footer from '@/components/Footer';

const quicksand = Quicksand({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700'] });

export const metadata: Metadata = {
  title: "biscato_frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} antialiased relative h-screen`}>
        <GoogleOAuthProvider clientId="<your_client_id>">
          {children}
          <Footer/>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
